### ISSUE TITLE
add a `strip` function

### ISSUE THREAD

**Issue by mitchweaver** [mitchweaver/bonsai#2]
the `CFLAGS=-s` and `LDFLAGS=-s` only work for stripping C-based executables as pointed out by people from the KISS project

To get around this, implement a function to use `strip` from bin/elf utils

------ also, find out how to get `strip`, as its not included by default in the toolchains gotten from http://musl.cc

**Comment by trvv** [comment]
`strip` is a GNU-ism so we'd have to port it from the GNU toolchain over to musl libc or use a compatibility layer or something...

**Comment by mitchweaver** [comment]
@trvv `strip` is in busybox, so its definitely portable. I'm sure I'll be able to find a solution somewhere.

**Comment by trvv** [comment]
wait it is? oof

**Comment by mitchweaver** [comment]
Huh... turns out the binary we've been using has `strip`.

It's `x86_64-linux-musl/bin/strip` deep in the pkgdir. :tada: I'll symlink it as `strip`.
