### ISSUE TITLE
readme should be changed from dll hell to dependency hell

### ISSUE THREAD

**Issue by HolyStephano** [MitchWeaver/bonsai#8]
in the readme you say "No .dll hell" when in reality it should be "No dependency hell"

The wiki page you link to, specifically, says "DLL Hell is the Windows ecosystem-specific form of the general concept dependency hell. "

**Comment by MitchWeaver** [comment]
I've heard the term `.dll hell` be used for all ecosystems that use dynamic linking. 

However if people want it changed, I'll change it. Let me know if you all agree or disagree with it.

**Comment by HolyStephano** [comment]
While people may use the term incorrectly to describe an identical issue, the general image of a distro will still benefit from a simple change. The page you link to only talks about windows, so using the catch-all term to describe the issue, OR using a linux-specific term might be the better way to go.

**Comment by MitchWeaver** [comment]
Fair enough. Closed by 06b95c3d6a5d48674132172051e4dcd5a15f6ee5.
