### ISSUE TITLE
Redundant use of GNU

### ISSUE THREAD

**Issue by HolyStephano** [MitchWeaver/bonsai#9]
Under Core Philosophy, you state in point 3 about a better c library, "GNU GLibc" which is redundant. glibc is already GNU libc. It's like saying PIN number. You're basically saying "GNU GNU lib c.

**Comment by MitchWeaver** [comment]
I think it is important to point out that it is *GNU's* GLibc not just "GNU Libc" as not all may be aware of the acronym, despite knowing what it is.

I think a compromise here is to state it as such.

**Comment by HolyStephano** [comment]
I think just stating "glibc" would be more than enough, or "GNU libc." Anyone looking into distros will already be confused by musl libc, i don't think it's too much for someone to look it up. Could also hyperlink out to the proper wiki articles/official pages for each.

**Comment by MitchWeaver** [comment]
I think `GNU's glibc` is sufficient, I'll add the hypertext to it as well.
